apiVersion: apps/v1
kind: Deployment
metadata:
  name: rso-payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rso-payments
  template:
    metadata:
      labels:
        app: rso-payments
    spec:
      containers:
        - image: mista123/payments-rso:latest
          name: katalog
          env:
            - name: db_user
              value: postgres
            - name: db_pw
              value: postgres
          ports:
            - containerPort: 8091
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: server
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: server
            initialDelaySeconds: 20
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: rso-payments
spec:
  type: ClusterIP
  ports:
    - port: 8091
      protocol: TCP
      targetPort: server
  selector:
    app: rso-payments