server:
  servlet:
    context-path: /
  port: 8091

spring:
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://83.212.127.63:5432/rso
    username: ${db_user}
    password: ${db_pw}
  jpa:
    hibernate:
      ddl-auto: create-drop

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
